### ISSUE TITLE
UI-REACT: Import Error with `@tonconnect/ui-react` in Next.js 14.0.2

### ISSUE THREAD

**Issue by num13ru** [ton-connect/sdk#117]
### Description
   I'm experiencing an import error when using `@tonconnect/ui-react` in a Next.js 14.0.2 application. The specific error is related to `TonConnectUIProvider` not being exported as expected.

   ### Error Message
   ```
   Attempted import error: 'TonConnectUIProvider' is not exported from '@tonconnect/ui-react' (imported as 'TonConnectUIProvider').

   Import trace for requested module:
   ./src/app/layout.tsx
   Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

   Check your code at layout.tsx:21.
    ⨯ Error: Unsupported Server Component type: undefined
       at stringify (<anonymous>)
    ⨯ Error: Unsupported Server Component type: undefined
       at stringify (<anonymous>)
   ```

   ### Code Snippet
   ```tsx
   import type { Metadata } from 'next';
   import { Inter } from 'next/font/google';
   import './globals.css';
   import { TonConnectUIProvider } from '@tonconnect/ui-react';

   const inter = Inter({ subsets: ['latin'] });

   const manifestUrl = 'https://my-next-app.vercel.app/tonconnect-manifest.json';

   export const metadata: Metadata = {
     title: 'Create Next App',
     description: 'Generated by create next app',
   };

   export default function RootLayout({
     children,
   }: {
     children: React.ReactNode;
   }) {
     return (
       <TonConnectUIProvider manifestUrl={manifestUrl}>
         <html lang="en">
           <body className={inter.className}>{children}</body>
         </html>
       </TonConnectUIProvider>
     );
   }
   ```

   ### Additional Information
   - `@tonconnect/ui-react` version: 2.0.0-beta.6
   - Next.js version: 14.0.2
   - Node.js version: v20.6.1

   I would appreciate any guidance or fixes for this issue. Thank you!

**Comment by liketurbo** [comment]
For next@13, it also yields an error, although a different one. It's worth noticing that i used "App Router (`app` directory)".
Next@12 with the "Pages router" works fine, though.

**Comment by hos** [comment]
This error seems to be introduced in [beta-5](https://github.com/ton-connect/sdk/commit/46642f649d11d10245f0e45a2eb27a3e4984769c)
beta-4 works with `App Router`

**Comment by thekiba** [comment]
It seems like the problem is related to a specific range of Next.js versions rather than an issue with TON Connect. 

To resolve this, you have to update or rollback the NextJS version:
-   ✅ Next.js 14.0.1 or earlier — works
-   ❌ Next.js 14.0.2-canary.1 to 14.0.3 — doesn't work
-   ✅ Next.js 14.0.4-canary.1 or later — works

Please use one of these solutions.

**Comment by antontuzov** [comment]
Adding 'use client'; on top of the page fixed the error to me.

**Comment by ArchimedesCrypto** [comment]
We should add the requirement of NextJs 14.0.4 to the readme. I spent hours trying to fix this until i found this
