### ISSUE TITLE
tonconnect-manifest hosted on a cdn service

### ISSUE THREAD

**Issue by k6c8e4** [ton-connect/sdk#12]
Hi people :)

I wanna know if can it be possible to use cdns to serve manifest file for TonConnect?
I wanna use this awesome library to create an extension for no-code app builder, which allows storing files in the root folder of the project only on a paid plan, which is useless in case I wanna build this extension without possibility to store tonconnect-manifest file in the root folder.
If it isn't possible now, will it be possible in the future maybe?

Some screens:

1. manifest file
![image](https://user-images.githubusercontent.com/48944515/214568914-2e4042b3-8961-4c0e-8f24-36bfb8542fc7.png)

2. after connect, deeplink converted into a QR code
![image0](https://user-images.githubusercontent.com/48944515/214569056-3831ea49-f927-4901-87fd-4b8aa15438db.png)

3. after scanning the QR code using Tonkeeper, in the connector "OnStatusChange" I'm getting in trouble )
![image1](https://user-images.githubusercontent.com/48944515/214569328-b2486491-a7b6-42ee-b9a4-7e857f3d93e5.png)

If you can help me figure it out how to use manifest file stored on a cdn service, it will be a great boost to bring no-code platforms to build dapps using TonConnector <3

Cheers

**Comment by siandreev** [comment]
Hi, you can specify the manifest URL in the `TonConnect` constructor parameters: 
`const connector = new TonConnect({ manifestUrl: 'https://<your-url>/tonconnect-manifest.json' });`

**Comment by inartin** [comment]
[](url)> Hi, you can specify the manifest URL in the `TonConnect` constructor parameters: `const connector = new TonConnect({ manifestUrl: 'https://<your-url>/tonconnect-manifest.json' });`

Hi, he is my teammate, we tried to fix it this way but we get same error.

**Comment by k6c8e4** [comment]
@siandreev yo,

I'm afraid I cannot use this case:
```
const connector = new TonConnect({ manifestUrl: 'https://<your-url>/tonconnect-manifest.json' });
```
1. because ```<your-url>``` means url of my aplication, but the tonconnect-manifest itself is hosted on an external CDN ```<cdn-url>```.
so if I will use ```const connector = new TonConnect({ manifestUrl: 'https://<cdn-url>/tonconnect-manifest.json' });``` it will throw the error mentioned in the initial question.

And the question remains the same. Can we host manifest file on an external cdn/storage then use the url in the connector? Or maybe it will be possible in the future?

Best regards,

**Comment by siandreev** [comment]
You can place the `ton-menifest.json` anywhere you want. It might be CDN or any hosting, not necessarily associated with the app. 
Please, check an [example](https://github.com/ton-connect/demo-dapp/blob/master/src/connector.ts#L5) and hit me, if the problem persists.

**Comment by k6c8e4** [comment]
@siandreev yo nice, this looks good to me.
I'll give it a try and will be back with a feedback.
Ty again :)

**Comment by k6c8e4** [comment]
@siandreev all good, sorry for troubles :)
thank you for implication 

best regards,
