### ISSUE TITLE
[SDK]: Emulation error: no response; status code: undefined; 

### ISSUE THREAD

**Issue by matthewmaclay** [ton-connect/sdk#133]
### Describe the bug

Successfully connected wallet via ton connect to TMA, but on confirm transaction see this screens in ton keeper and tg wallet
![telegram-cloud-photo-size-2-5302995931848890781-y](https://github.com/ton-connect/sdk/assets/36126770/80da5d47-feea-4d0d-8ad2-fcb63c8ad8c8)
![telegram-cloud-photo-size-2-5303294333291717521-y](https://github.com/ton-connect/sdk/assets/36126770/c627f91a-7799-4a46-8c6b-f570f34ca037)

### Expected behavior

Transcation will approve successfully.

### Current behavior

Wallet see transaction, but i cant approve it

### Steps to Reproduce

-

### Environment

└─┬ @tonconnect/ui@2.0.0
  └─┬ @tonconnect/sdk@3.0.0
    ├── @tonconnect/isomorphic-eventsource@0.0.2
    ├── @tonconnect/isomorphic-fetch@0.0.3
    └── @tonconnect/protocol@2.2.6

**Comment by matthewmaclay** [comment]
This happened because I didn't form the payload correctly
```
      sendTransaction({
        messages: [
          {
            address: process.env.NEXT_PUBLIC_WALLET_ADDRESS as string,
            amount: toNanoTon(0.1),
            payload: btoa(`ID:${order.id}`),
          },
        ],
        validUntil: Math.floor(Date.now() / 1000) + 120, // 60 sec
      });
```

And right way is:
```
const transactionComment = (text: string) => {
  const cell = beginCell()
    .storeUint(0x00000000, 32)
    .storeStringTail(text)
    .endCell();

  const boc = cell.toBoc();
  return boc.toString("base64");
};
tonConnect.sendTransaction({
messages: [
    {
    address: process.env.NEXT_PUBLIC_WALLET_ADDRESS as string,
    amount: toNanoTon(order.amount),
    payload: transactionComment(`ID:${order.id}`),
    },
],
validUntil: Math.floor(Date.now() / 1000) + 120, // 60 sec
});
```

**Comment by huangyuanda** [comment]
hello,I have same problem.but i used C# sdk.i can't understand how to resolve it
