### ISSUE TITLE
`TransactionCanceledModal` is not getting closed when the "close" button is pressed

### ISSUE THREAD

**Issue by arterialist** [ton-connect/sdk#15]
When transaction is canceled by the user and the corresponding notification pops up, it can't be closed if user clicks on the "close" button.

Environment:
React 18.2.0
Next.js 13.1.5
tonconnect/ui-react 0.0.13

![image](https://user-images.githubusercontent.com/37044735/214842463-a05f1e65-2cc9-4b89-be7a-34b824853cde.png)

**Comment by siandreev** [comment]
Hi @arterialist, thank for your feedback. Actually, this is not a 'close' button, it is just 'cancelled action' icon :) 
We we will redesign it so that it does not confuse users
