### ISSUE TITLE
UI-REACT: Wrong modal in mobile

### ISSUE THREAD

**Issue by abolfazlakbarzadeh** [ton-connect/sdk#156]
### Describe the bug

not working correctly on a variety of mobile screens, some mobile screens are wider than 440px so the modal shows a QR Code to scan instead of displaying wallets to select and navigate into the related app

### Expected behavior

on any mobile device should show a modal to select wallet and then navigate to the app to confirm connection or payment

### Current behavior

some mobile screens are wider than 440px so the modal shows a QR Code to scan instead of displaying wallets to select and navigate into the related app

### Steps to Reproduce

1- use a mobile for example POCO x3 pro, this model's screen width is ~490px
2- open up the webpage that contains the connect or pay button and click on it.
3- so you see a modal that shows a QR Code to scan

### Environment

└─┬ @tonconnect/ui-react@2.0.0
  └─┬ @tonconnect/ui@2.0.0
    └─┬ @tonconnect/sdk@3.0.0
      ├── @tonconnect/isomorphic-eventsource@0.0.2
      ├── @tonconnect/isomorphic-fetch@0.0.3
      └── @tonconnect/protocol@2.2.6
      
      Android 10
      Chrome

**Comment by thekiba** [comment]
Please upgrade to `@tonconnect/ui-react@2.0.2` to fix this issue.

Let me know if the problem persists.

**Comment by abolfazlakbarzadeh** [comment]
the current version of the installed package is already 2.0.2, I had to fix this by myself and fix another bug related to redirecting to the wallet in IOS OS, I just made a pull request for that #157
