### ISSUE TITLE
React-UI: Identifier '...' has already been declared

### ISSUE THREAD

**Issue by arterialist** [ton-connect/sdk#16]
TonConnect ReactUI fails to initialize when NextJs app is built and served statically. **This doesn't happen as long as the app is ran with `yarn dev`**

**Steps to reproduce:**

1. `yarn create next-app --typescript` (any name, use eslint - yes, use src/ - yes, use app/ - no, import alias - default)
2. `yarn add @tonconnect/ui-react`
3. Wrap app with `TonConnectUIProvider` as per docs
4. `yarn build`
5. `yarn start`
6. Go to localhost:3000

**Result:**

`Uncaught SyntaxError: Identifier 'r' has already been declared (at _app-6faa08e70223d641.js:5:26019)` in the console

**package.json dependencies:**

```
"dependencies": {
    "@next/font": "13.1.5",
    "@tonconnect/ui-react": "^0.0.13",
    "@types/node": "18.11.18",
    "@types/react": "18.0.27",
    "@types/react-dom": "18.0.10",
    "eslint": "8.32.0",
    "eslint-config-next": "13.1.5",
    "next": "13.1.5",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "typescript": "4.9.4"
  }```

**Comment by arterialist** [comment]
Note: the same exact issue happens even when using the @tonconnect/ui package in the same environment. Mounting it inside `useEffect` is enough to trigger the issue.

**Comment by arterialist** [comment]
After a bit of trial and error, this issue seems to be directly related to the NextJs version. TonConnect works just fine on NextJs < 13. Version 13 introduced a new bundler and I think it's the reason of the issue above.

While not being a direct TonConnect issue, I think it's still important to resolve it as every latest version of NextJs docs is referencing the version 13.

**Comment by siandreev** [comment]
I faced with the similar problem. The solution was to update or rollback the NextJS version:
✅ NextJS `12.х.х` -- works 
❌ NextJS `13.0.х` -- doesn't work
✅  NextJS `13.1.1` -- works
