### ISSUE TITLE
UI-REACT: build error 

### ISSUE THREAD

**Issue by NarekChang** [ton-connect/sdk#161]
### Describe the bug

Build with non-existent files.
It seems to be a conflict of npm package versions. You may not have updated some part of the public packages.

### Expected behavior

No assembly error

### Current behavior

WARNING in ./node_modules/@tonconnect/sdk/lib/esm/index.mjs
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/.../frontend/node_modules/@tonconnect/sdk/src/utils/types.ts' file: Error: ENOENT: no such file or directory, open '/.../frontend/node_modules/@tonconnect/sdk/src/utils/types.ts'

### Steps to Reproduce

1. npm i @tonconnect/ui-react
2. Wrapped HOC to TonConnectUIProvider
3. run `react-scripts start`

(use react-cli)

### Environment

ts-config

```
{
  "compilerOptions": {
    "baseUrl": ".",
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "paths": {
      "features": ["./src/features"]
    },
    "typeRoots": ["./node_modules/telegram-webapps"]
  },
  "include": ["**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}

```

**Comment by Srr233** [comment]
Hello. I have the same issue here with @tonconnect/sdk

I'm using react but with @tonconnect/sdk instead ui-react.

ts config
`{
  "compilerOptions": {
    "baseUrl": "src",
    "target": "ES2015",
    "module": "esnext",
    "lib": ["dom", "esnext"],
    "allowJs": false,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "esModuleInterop": true,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "strict": false,
    "sourceMap": true,
    "incremental": true
  },
  "exclude": ["node_modules", "src/**/*.css"],
  "include": ["src/**/*.tsx", "src/**/*.ts", "src/custom.d.ts"]
}
`
