### ISSUE TITLE
Error: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function

### ISSUE THREAD

**Issue by Aurora3014** [ton-connect/sdk#200]
### Describe the bug

![image](https://github.com/ton-connect/sdk/assets/166276339/6c3e9bb8-d2d1-414b-b4f7-843234162164)

### Expected behavior

The page should be rendered.

### Current behavior

I installed @tonconnect/ui-react@2.0.6 with next.js 14.2.4,
But when I use TonconnectUiProvider in layout, this error comes out.

### Steps to Reproduce

Make new Nextjs project with 14.2.4
install @tonconnect/ui-react
Use TonConnectUIProvider in Layout.tsx

Then this error comes out

### Environment

    "@tonconnect/ui-react": "^2.0.6",
    "@next/bundle-analyzer": "^14.2.3",
    "@next/third-parties": "^14.2.3",
    "@sentry/nextjs": "^8",
    "next": "^14.2.3",
    "next-themes": "^0.3.0",
    "nextjs-progressbar": "^0.0.16",
    "nextjs-toploader": "^1.6.12",

**Comment by Aurora3014** [comment]
I just solved this problem on my own :)
Do not install tonconnect-ui-react module with npm i.
Copy all the sources from this repo 
https://github.com/DmitryKodolbenko/tonconnect-react
goto src folder, and copy all files  into your next js src folder.
("Attention, you should add "use client" to all the files in ton-connect.")
then import components from that module.

Happy coding:)

**Comment by VanThuan76** [comment]
It's still not working, bro :(

![Uploading Ảnh màn hình 2024-07-20 lúc 21.53.18.png…]()

**Comment by broAir** [comment]
Having same issue with the nextjs

**Comment by 0xDmitry** [comment]
Same issue, next.js

**Comment by 0xDmitry** [comment]
@thekiba can you reopen this one?

**Comment by 0xDmitry** [comment]
Nvm, found a solution. Just need to wrap TonConnectUIProvider into client component and make sure that you use all imported components like TonConnectButton only inside client components as well.

**Comment by alexcraviotto** [comment]
> Nvm, found a solution. Just need to wrap TonConnectUIProvider by client component and make sure that you use TonConnectButton only inside client components as well.

Can you share an example code snippet? I'm stucked on this problem.

**Comment by 0xDmitry** [comment]
In the beginning of the file where you import TonConnectButton you need to add "use client" directive. Also you need to create your own TonConnectProvider that will work on the client like this:

`"use client"

import { TonConnectUIProvider } from "@tonconnect/ui-react"

const manifestUrl = "your URL"

export const TonConnectProvider = ({
  children,
}: {
  children: React.ReactNode
}) => (
  <TonConnectUIProvider manifestUrl={manifestUrl}>
    {children}
  </TonConnectUIProvider>
)`

**Comment by 0xDmitry** [comment]
> > Nvm, found a solution. Just need to wrap TonConnectUIProvider by client component and make sure that you use TonConnectButton only inside client components as well.
> 
> Can you share an example code snippet? I'm stucked on this problem.

In the beginning of the file where you import TonConnectButton you need to add "use client" directive. Also you need to create your own TonConnectProvider that will work on the client like this:

```
"use client"

import { TonConnectUIProvider } from "@tonconnect/ui-react"

const manifestUrl = "your URL"

export const TonConnectProvider = ({
  children,
}: {
  children: React.ReactNode
}) => (
  <TonConnectUIProvider manifestUrl={manifestUrl}>
    {children}
  </TonConnectUIProvider>
)
```

**Comment by alexcraviotto** [comment]
> > > Nvm, found a solution. Just need to wrap TonConnectUIProvider by client component and make sure that you use TonConnectButton only inside client components as well.
> > 
> > 
> > Can you share an example code snippet? I'm stucked on this problem.
> 
> In the beginning of the file where you import TonConnectButton you need to add "use client" directive. Also you need to create your own TonConnectProvider that will work on the client, like this:
> 
> ```
> "use client"
> 
> import { TonConnectUIProvider } from "@tonconnect/ui-react"
> 
> const manifestUrl = "your URL"
> 
> export const TonConnectProvider = ({
>   children,
> }: {
>   children: React.ReactNode
> }) => (
>   <TonConnectUIProvider manifestUrl={manifestUrl}>
>     {children}
>   </TonConnectUIProvider>
> )
> ```

Thank you! In the end I created a ‘Root’ component to wrap it the way you said. Have a nice day!

**Comment by 0xDmitry** [comment]
> > > > Nvm, found a solution. Just need to wrap TonConnectUIProvider by client component and make sure that you use TonConnectButton only inside client components as well.
> > > 
> > > 
> > > Can you share an example code snippet? I'm stucked on this problem.
> > 
> > 
> > In the beginning of the file where you import TonConnectButton you need to add "use client" directive. Also you need to create your own TonConnectProvider that will work on the client, like this:
> > ```
> > "use client"
> > 
> > import { TonConnectUIProvider } from "@tonconnect/ui-react"
> > 
> > const manifestUrl = "your URL"
> > 
> > export const TonConnectProvider = ({
> >   children,
> > }: {
> >   children: React.ReactNode
> > }) => (
> >   <TonConnectUIProvider manifestUrl={manifestUrl}>
> >     {children}
> >   </TonConnectUIProvider>
> > )
> > ```
> 
> Thank you! In the end I created a ‘Root’ component to wrap it the way you said. Have a nice day!

Just be careful with "use client" directive. If you specify your root component as client all children will be client too.
