### ISSUE TITLE
[UI-REACT]: wallet, connection status etc should be returned with their up to date state from useTonConnectUI

### ISSUE THREAD

**Issue by shaharyakir** [ton-connect/sdk#23]
Currently you'd have to subscribe to events with `onStatusChange`, but it's contradictory to how hooks are expected to work.

It'd make more sense that whenever any connection state changes, useTonConnectUI would return it (similar to useState).

**Comment by siandreev** [comment]
Hi @shaharyakir , thanks for your question. You shouldn't can  use `useTonConnectUI ` for `onStatusChange` subscriptions. This hook is only designed for actions calls like `sendTransaction`, or TonConnectUI configuration changing. 
If you need to get actual wallet, you should use `useTonWallet`  https://github.com/ton-connect/sdk/tree/main/packages/ui-react#usetonwallet

**Comment by siandreev** [comment]
When you use tonconnect/ui-react you should not use `onStatusChange` at all. To send a transaction you can use just `const result = await tonConnectUI.sendTransaction(transaction)`. When user approves the transaction it the wallet, the promise will resolves. [See details](https://github.com/ton-connect/sdk/tree/main/packages/ui#send-transaction)

**Comment by shaharyakir** [comment]
In that case, I'd suggest to avoid returning wallet details and the onStatusChange event handler from the useTonConnectUI hook (if you're not supposed to use them all they do is create confusion).

**Comment by AllDayAlone** [comment]
Same confusion was in our team
