### ISSUE TITLE
Response id N doesn't match any request's id

### ISSUE THREAD

**Issue by dmitrydrynov** [ton-connect/sdk#24]
I got an error `Error: [TON_CONNECT_SDK_ERROR] Response id 12 doesn't match any request's id` after transaction rejected.
How can I fix it?

**Comment by siandreev** [comment]
Hi! This error can occur when an application is not expecting a response to a request. For example, after reloading the page, or if you have several tabs open with the application. Handle and ignore this error

**Comment by Shashank-product** [comment]
How can we resolve it? I didn't find an appropriate solution.
![photo1675954062](https://user-images.githubusercontent.com/109502292/217863662-b9fec3dd-ff65-45e3-8f15-1f64e52bbd00.jpeg)
