### ISSUE TITLE
Wallet Signature

### ISSUE THREAD

**Issue by calvin-yang** [ton-connect/sdk#30]
Hello, how should I call up the signature? For example, TonMask provides a method (ton_requestWallets)

**Comment by siandreev** [comment]
Hi. If you need to authorize in your backend, `ton_proof` can be used: https://github.com/ton-connect/sdk/tree/main/packages/sdk#backend-authorization

**Comment by calvin-yang** [comment]
Is there any python sdk?

**Comment by siandreev** [comment]
> Is there any python sdk?

Unfortunately, we do not plan to create such a package ourselves in the near future. However, we will gladly include community developments in the SDK.
