### ISSUE TITLE
UI-REACT:  reconnect not work on broswer inside tonkeeper wallet

### ISSUE THREAD

**Issue by LeoWangJ** [ton-connect/sdk#38]
When I use the  [demo-dapp-with-react-ui](https://github.com/ton-connect/demo-dapp-with-react-ui)  to log in on the browser inside TonKeeper wallet, clicking refresh does not reconnect and it seems like localStorage key `ton-connect-storage_bridge-connection` has been deleted, causing the inability to reconnect, but other localStorage key still exist.

How can I solve the issue of the refresh button not reconnecting automatically in my application?

https://user-images.githubusercontent.com/17901443/224413128-e6f85b8a-1940-4d1a-a343-e46ec5bfaa0c.mp4

**Comment by siandreev** [comment]
Hi @LeoWangJ ! Seems like there is a bug in the Tonkeeper. We will take a look.

**Comment by siandreev** [comment]
Moved to the Tonkeeper's bugs
