### ISSUE TITLE
[UI-REACT] TonConnnectButton is gone after moving between pages

### ISSUE THREAD

**Issue by Jay-Yay** [ton-connect/sdk#39]
**Describe the bug**
TonConnectButton disappears once I move to another page.

1) When the application is initiated first, the TonConnectButton shows.
<img width="1512" alt="Screen Shot 2023-03-15 at 2 10 45 PM" src="https://user-images.githubusercontent.com/109274779/225374726-a79709fc-cb3b-483c-b00e-290aba931aec.png">

2) However, when moving to another page, the button disappears. From the console, the top parent div for TonConnectButton is loaded but the remaining components are not loaded for the button. 
<img width="1512" alt="Screen Shot 2023-03-15 at 2 11 06 PM" src="https://user-images.githubusercontent.com/109274779/225375068-d09ff608-8009-43a9-bfc7-11ceaf6803a4.png">
<img width="1510" alt="Screen Shot 2023-03-15 at 2 11 19 PM" src="https://user-images.githubusercontent.com/109274779/225376806-cc4d5095-bdd7-4298-b096-59811f380442.png">
<img width="1510" alt="Screen Shot 2023-03-15 at 2 11 37 PM" src="https://user-images.githubusercontent.com/109274779/225375094-e636446c-58dd-4fce-ae24-6598c8446c59.png">

3. When I refreshed the browser with 'command + R', the button appears again.
<img width="1503" alt="Screen Shot 2023-03-15 at 2 12 00 PM" src="https://user-images.githubusercontent.com/109274779/225375423-f23ae6f9-f786-44f4-af3f-571665cd4096.png">

**To Reproduce**
1. Put the TonConnectButton on each two pages 
2. Run the application and move to another page
3. See that the TonConnectButton disappeared.

**Expected behavior**
The TonConnectButton should be loaded in the same way as it did when initializing the application.

**Screenshots**
 - OS: macOS 12.3.1
 - Browser: Chrome
 - Package version: 0.0.14
 - My project: react with next.js ("react": "18.2.0", "next": "13.2.3")

**Additional context**
TonConnectButton is included in the 'Header' component and it is loaded from each page (index.tsx, discover.tsx).

```
// component/Header.tsx
import { TonConnectButton } from '@tonconnect/ui-react';
...

const Header = (props: { menuName: EHeaderMenu }) => {
  return (
    <StHeader>
      ....
      <TonConnectButton />
    </StHeader>
  )
}
```

```
// page/index.tsx
const Home: NextPage = () => {
  return (
    <StWrapper>
      <Header />
    </StWrapper>
  )
}
...
```

```
// page/discover.tsx
const Discover: NextPage = () => {
  return (
    <StWrapper>
      <Header />
    </StWrapper>
  )
}
```

I have tried to solve this issue but decided to ask you after 2-day debugging..🥹
Thank you for your work in advance.

**Comment by siandreev** [comment]
Hi @Jay-Yay . Please recheck this with `@tonconnect/ui-react`  `1.0.0-beta.4` version
