### ISSUE TITLE
How can I append custom message to transaction?

### ISSUE THREAD

**Issue by OlegShalagin** [ton-connect/sdk#52]
I wanted to send some data with transaction and check it on server.
Need help.

```
const defaultTx = {
        validUntil: Date.now() + 1000000,
        messages: [
            {
                address: '0:0####',
                amount: '20000000',
                payload: 'causes error',
                stateInit: 'causes error'
            }
        ],
        message: 'message ? does not appear'
    };

const result = await connector.sendTransaction(defaultTx);
```

**Comment by bogdan-kotlubay** [comment]
Yea, tonkeeper response error Warning: Unknown error if sended with payload.

**Comment by siandreev** [comment]
Hi @

**Comment by siandreev** [comment]
If you need to send a message with a comment, you should create cell with op=0, add your comment, convert this cell to Base64, and pass result as the message payload

**Comment by OlegShalagin** [comment]
> If you need to send a message with a comment, you should create cell with op=0, add your comment, convert this cell to Base64, and pass result as the message payload

give a code example please

**Comment by siandreev** [comment]
```const payload = beginCell().storeUint(0, 32).storeStringTail("YOUR_COMMENT").endCell().toBoc().toString("base64")```

**Comment by siandreev** [comment]
@bogdan-kotlubay @OlegShalagin is that what you were looking for?

Full example 

```

const defaultTx = {
        validUntil: Date.now() + 1000000,
        messages: [
            {
                address: '0:0####',
                amount: '20000000',
                payload: beginCell().storeUint(0, 32).storeStringTail("YOUR_COMMENT").endCell().toBoc().toString("base64")
            }
        ]
    };

const result = await connector.sendTransaction(defaultTx);


```

**Comment by OlegShalagin** [comment]
> @OlegShalagin is that what you were looking for?
@siandreev looks great, i`ll try it, thank you!

**Comment by bogdan-kotlubay** [comment]
> @bogdan-kotlubay @OlegShalagin is that what you were looking for?
> 
> Full example
> 
> ```
> 
> const defaultTx = {
>         validUntil: Date.now() + 1000000,
>         messages: [
>             {
>                 address: '0:0####',
>                 amount: '20000000',
>                 payload: beginCell().storeUint(0, 32).storeStringTail("YOUR_COMMENT").endCell().toBoc().toString("base64")
>             }
>         ]
>     };
> 
> const result = await connector.sendTransaction(defaultTx);
> ```

yea, thanks!
