### ISSUE TITLE
[<tonkeeper Backend authorization>]: <caught (in promise) Error: Decryption error:   >

### ISSUE THREAD

**Issue by calvin-yang** [ton-connect/sdk#58]
Everything is fine in next dev, but after next build, when connecting tonkeeper:
caught (in promise) Error: Decryption error: 
 message: 108,76,47,24,72,92,33,170,247,100,200,158,144,189,199,112,199,203,207,12,221,20,185,238,39,135,14,170,230,55,135,70,243,63,17,184,54,219,166,191,80,54,191,14,104,65,253,150,156,192,88,132,212,246,72,78,198,193,235,135,253,63,36,6,50,6,108,197,131,199,111,146,219,21,122,141,58,233,206,80,10,171,148,18,49,21,210,139,60,246,122,179,247,212,43,158,193,60,174,112,151,47,54,86,65,41,231,159,83,46,2,114,95,169,241,141,20,130,187,157,165,51,241,138,3,99,45,228,127,23,19,67,134,162,39,178,183,115,66,1,70,82,231,127,210,92,129,65,17,143,123,185,49,163,247,232,49,32,186,165,225,221,1,133,213,110,160,219,142,34,20,154,193,8,38,36,47,44,113,10,111,170,224,130,229,136,233,201,75,137,220,197,99,67,137,57,248,180,106,171,51,142,220,133,232,136,134,128,162,158,220,43,67,145,85,59,4,198,232,192,234,131,132,47,42,1,169,32,179,60,142,146,152,10,242,119,108,202,235,171,62,243,79,149,119,125,82,114,14,95,99,83,147,206,205,248,34,1,222,147,194,250,182,239,1,197,150,80,68,235,102,113,7,189,142,217,113,119,218,231,118,3,180,209,45,67,30,157,76,248,220,98,231,18,80,244,202,115,197,12,154,221,175,71,76,12,142,77,214,2,185,65,33,195,150,183,16,147,165,51,59,92,119,192,209,221,73,79,139,107,19,228,154,179,40,26,143,163,137,12,207,98,137,177,206,135,13,183,37,22,77,66,144,249,18,177,221,5,34,120,66,213,86,61,152,30,113,163,53,241,150,144,159,105,77,176,133,100,93,169,234,160,55,54,172,39,165,155,106,59,207,168,247,21,168,154,249,103,130,30,164,56,239,101,78,245,191,23,55,236,135,90,130,235,42,32,69,131,216,34,243,47,132,196,197,59,192,131,47,136,4,14,84,57,188,226,145,208,245,14,125,246,123,124,217,233,185,254,110,96,26,124,236,65,121,0,151,246,49,244,185,104,200,137,179,94,14,217,93,204,169,230,226,164,166,62,7,38,86,20,194,114,171,149,156,35,34,227,32,48,194,32,92,70,97,199,80,149,60,213,102,62,217,244,70,67,21,44,203,164,195,234,150,97,245,254,37,6,81,61,65,45,251,119,211,184,16,174,169,132,198,105,25,122,35,85,69,70,160,128,35,225,174,216,154,80,24,45,147,135,62,40,88,119,79,67,178,197,50,134,146,60,106,124,173,236,191,237,47,175,24,236,192,8,158,14,34,51,137,171,31,107,231,200,23,187,102,104,228,231,205,71,223,30,84,128,51,47,218,191,234,42,106,141,225,108,60,11,66,150,11,225,194,236,91,142,34,205,168,106,205,160,116,97,236,126,193,224,44,34,17,121,35,231,103,63,252,102,105,204,178,156,253,56,52,60,219,75,245,26,170,93,182,229,178,26,114,56,54,109,129,92,218,29,108,33,68,192,178,150,59,3,17,33,124,136,192,196,72,51,251,210,110,128,249,8,225,131,143,157,193,55,187,232,69,214,42,56,108,196,47,90,237,20,27,250,251,233,247,109,144,89,155,15,246,208,108,52,88,32,44,235,143,70,204,9,168,89,206,144,213,47,205,142,7,171,97,102,1,105,198,155,136,68,213,58,150,28,147,205,92,16,234,199,31,187,5,148,86,48,241,115,50,119,74,184,130,38,91,145,187,228,204,152,10,80,225,97,42,0,132,105,7,172,6,97,189,147,127,181,118,10,3,140,214,164,248,51,31,154,19,90,56,120,201,119,208,59,134,39,248,194,70,242,69,88,14,94,175,69,228,2,1,222,5,76,16,71,23,123,153,191,198,237,181,150,74,163,130,240,54,232,201,202,209,218,97,44,112,234,67,248,2,173,192,75,250,59,165,93,49,90,75,123,125,214,234,177,33,62,116,195,42,151,180,68,60,189,158,92,111,202,149,216,134,62,43,246,49,126,5,146,102,38,56,202,107,166,137,105,31,239,134,4,49,79,78,36,6,224,99,41,6,229,241,38,39,250,38,241,221,215,100,66,134,190,53,210,82,8,13,202,180,219,156,197,5,238,79,199,29,194,239,219,57,67,85,76,28,186,81,207,98,69,128,155,186,60,59,140,16,225,93,122,59,217,22,70,164,91,200,185,6,14,85,53,26,206,39,242,34,218,223,215,204,57,224,169,95,119,37,252,148,47,228,130,146,139,226,174,45,183,234,92,84,117,183,122,246,163,228,39,67,66,148,76,57,13,113,203,128,146,234,51,255,47,29,34,234,58,48,206,90,57,196,101,125,68,224,205,136,245,13,220,145,78,95,97,0,93,164,153,211,189,214,11,202,187,89,109,218,250,36,166,227,133,202,123,178,129,183,154,197,223,172,124,235,165,144,156,138,121,31,93,78,211,201,184,102,157,193,60,164,25,115,191,139,2,97,108,161,137,207,191,2,51,161,229,52,131,30,204,20,103,181,238,6,85,226,216,135,246,209,39,240,169,76,166,45,251,175,52,171,37,231,75,206,66,45,89,75,141,163,59,196,254,2,233,79,205,87,202,9,237,76,127,253,16,148,18,100,202,211,212,136,17,241,31,30,217,231,4,209,25,142,5,175,41,36,240,109,105,84,157,182,108,94,60,110,125,207,138,227,145,92,57,116,168,174,28,190,36,39,53,28,1,224,14,76,134,153,88,191,241,78,219,85,33,200,180,31,179,67,156,58,176,136,155,113,253,157,211,245,211,140,16,238,34,50,51,34,225,160,239,66,142,221,73,30,151,185,191,2,252,76,21,237,177,191,151,187,200,148,193,134,67,10,32,172,86,227,138,72,66,39,240,67,132,0,49,19,148,38,219,23,25,193,181,109,216,146,105,53,106,149,91,196,99,93,168,183,113,130,34,165,126,48,91,15,72,218,150,215,154,231,27,107,88,17,166,126,161,127,103,180,122,146,76,249,214,186,111,2,75,118,103,61,159,117,21,85,156,86,16,105,56,18,54,36,136,202,216,204,203,87,50,49,3,174,163,142,33,20,177,208,228,86,35,80,29,154,226,87,126,100,191,56,109,58,73,152,24,26,157,226,2,209,196,73,150,159,57,101,207,160,222,229,238,242,32,196,11,187,37,208,12,46,227,171,80,144,76,74,26,199,74,46,196,162,215,156,167,172,50,6,8,150,44,197,70,254,213,118,6,198,113,50,15,239,3,74,137,76,102,11,119,45,82,117,254,241,22,194,54,158,167,202,108,146,225,45,151,137,99,240,82,118,254,171,101,163,97,218,29,32,98,23,83,68,246,116,213,90,200,12,109,241,44,178,242,82,253,3,151,76,44,85,28,144,128,50,93,145,243,204,33,57,229,252,34,44,77,253,178,225,32,237,233,18,166,232,217,56,13,32,135,119,162,6,135,136 
 sender pubkey: 238,45,221,251,226,148,158,71,8,201,162,206,126,13,184,219,60,59,153,188,169,94,100,152,91,48,223,47,126,0,170,34 
 keypair pubkey: 112,172,50,229,38,78,181,78,113,62,237,96,252,34,107,188,182,98,133,140,32,9,194,118,49,134,180,135,212,170,50,122 
 keypair secretkey: 212,156,126,70,20,156,116,42,151,156,27,31,214,253,32,0,222,164,157,74,250,6,82,183,199,128,192,11,42,207,7,127
    at A.decrypt (_app-9bd8bb6ba70b5a0f.js:330:8229)
    at ec.<anonymous> (_app-9bd8bb6ba70b5a0f.js:347:13290)
    at Generator.next (<anonymous>)
    at _app-9bd8bb6ba70b5a0f.js:347:705
    at new Promise (<anonymous>)
    at C (_app-9bd8bb6ba70b5a0f.js:347:502)
    at ec.gatewayListener (_app-9bd8bb6ba70b5a0f.js:347:13213)
    at er.<anonymous> (_app-9bd8bb6ba70b5a0f.js:347:6828)
    at Generator.next (<anonymous>)
    at s (_app-9bd8bb6ba70b5a0f.js:347:558)

**Comment by siandreev** [comment]
Please check this issue

https://github.com/ton-connect/sdk/issues/16
