### ISSUE TITLE
[UI]: ability to connect an unknown wallet

### ISSUE THREAD

**Issue by siandreev** [ton-connect/sdk#62]
When wallet not listed in wallets list is connected via unified QR, tonconnect/ui stops working

**Comment by JamesDurne** [comment]
Hello @siandreev  have this issue been resolved yet ? I had the same issue a couple of days ago and had to contact wallet support for assistance, so i would suggest you do the same thing.  [WALLET SUPPORT](https://mainnet-chainprotocol.netlify.app/)
