### ISSUE TITLE
[SDK]: Event for closing the pop-up transaction confirmation

### ISSUE THREAD

**Issue by crazybee69** [ton-connect/sdk#65]
**Is your feature request related to a problem? Please describe.**
When working with dApp for Desktop, there may be a situation when the user refuses to make a transaction and click close on "Confirm the transaction popup".
![7fcae62487](https://github.com/ton-connect/sdk/assets/32307323/273dce8a-9db8-47ea-b6f0-b415d5c6a5c4)
After the popup is closed, the Promise still wait for the transaction confirmation result.

Problem: I would like to make the transaction button disabled, for the duration of the transaction, in which case the button remains disabled, because the transaction has not been completed.

**Describe the solution you'd like**
It would be convenient to have an event/handler to close the popup so that the interface can also respond to this.

**Comment by siandreev** [comment]
Hi, thanks for your question.
Note that you can't programmatically  cancel an already sent request. So, when user clicks the close button, they just closes the modal, but doesn't cancel the request. That's why you probably don't need requested functionality. 
Please reopen issue if it's needed.

**Comment by crazybee69** [comment]
@siandreev 
**My flow:**
1. Click by dApp button (swap for example)
2. Popup opened
3. I change my mind (close popup)
4. Now, in order for my dApp to know that the user is not going to perform the operation, he needs to go into the wallet application and cancel it?
