### ISSUE TITLE
[UI]: The name of the wallet does not fit

### ISSUE THREAD

**Issue by troman29** [ton-connect/sdk#66]
**Describe the bug**
The name of the MyTonWallet does not fit in the interface, although it is not long.

**To Reproduce**
1. Go to https://dns.ton.org or other site with TonConnect UI
2. Click on 'Connect wallet'
3. See cutted 'MyTonW...'

**Expected behavior**
The name is displayed in full.

**Screenshots**
 - Any desktop OS
 - Any browser
 
![image](https://github.com/ton-connect/sdk/assets/104140659/cdd18869-c3d1-4c99-9f71-b838a59963cd)

**Comment by siandreev** [comment]
Fixed in `@tonconnect/ui 2.0.0-beta.0`
