### ISSUE TITLE
[UI]: back button doesn't close modal popup

### ISSUE THREAD

**Issue by stels-cs** [ton-connect/sdk#70]
**Describe the bug**
For android users it's common to close popups by press back button on system ui. But it doesn't close connect popup.
<img width="385" alt="image" src="https://github.com/ton-connect/sdk/assets/8437497/3c1eb2ef-023f-427c-8c38-e0b20a4c790d">

**To Reproduce**
0. You need android phone
1. Go to https://ton-connect.github.io/demo-dapp-with-react-ui/
2. Click on "Connect Wallet"
3. Click on Back button
4. Popup will not close

**Expected behavior**
Popup should close like in Tonkeeper when we see transaction info
<img width="366" alt="image" src="https://github.com/ton-connect/sdk/assets/8437497/d3efe0e2-58fa-43ee-ab84-960c39a1b191">

**Comment by stels-cs** [comment]
Нельзя вот так просто использовать window.history.pushState({}, '');
это сломает навигацию на сайтах.
Нужна возможность интеграции с роутером который используется в основном приложении

**Comment by thekiba** [comment]
Вместе с @stels-cs предметно обсудили вопрос и пришли к следующим выводам:

1. Модальные окна открываются с оверлеем и, по дизайну, должны быть "главными". Пользователь не должен ожидать, что его куда-то перебросит, и никто не должен что-либо записывать в стейт.

2. Важно учитывать, что `window.history` — это общий объект для всего приложения, и его манипуляции могут быть неожиданностью для разработчика. Поэтому стоит предоставить возможность контролировать поведение. Особенно это важно для TWA, где навигация может работать иначе, чем в браузере.

3. Был выявлен кейс, когда изменение истории в событии `onStatusChange` приводит к откату истории, потому что событие `onStatusChange` происходит раньше, чем срабатывает `history.back`.

В связи с этим было принято решение:

1. Добавить проверку, является ли текущее состояние `window.history` "пропатченным" SDK или нет, чтобы избежать случайного отката истории.

2. Сделать фичу отключаемой, чтобы разработчики, столкнувшиеся с проблемами, могли отключить её и сделать все необходимые действия вручную. Это особенно актуально для крупных проектов с сложной навигацией.
