### ISSUE TITLE
[UI-REACT]: Getting ContractProvider/Sender or KeyPair from the session

### ISSUE THREAD

**Issue by Lukasz2891** [ton-connect/sdk#77]
Is there any way of getting `ContractProvider`/`Sender` attached to the connected account like the one from `ton-core`? Or even `KeyPair` like from `ton-crypto/dist/primitives/nacl`? The session contains the `sessionCrypto `with the `KeyPair` but that's not available in a public interface :(

```js
export interface ContractProvider {
    getState(): Promise<ContractState>;
    get(name: string, args: TupleItem[]): Promise<ContractGetMethodResult>;
    external(message: Cell): Promise<void>;
    internal(via: Sender, args: { value: bigint | string, bounce?: Maybe<boolean>, sendMode?: SendMode, body?: Maybe<Cell | string> }): Promise<void>;
}
```

**Comment by siandreev** [comment]
Session crypto keypair is not a user's wallet keypair. You can't get a user's keypair in the dApp because wallet doesn't share it with the dApp. Could you explain why do you need it?
