### ISSUE TITLE
[UI-REACT]: Fail to connected using tonkeeper on Android devices (Telegram for Android v10.0.4 (3802))

### ISSUE THREAD

**Issue by tuminzee** [ton-connect/sdk#78]
**Describe the bug**
Unable to connect with tonkeeper app on Android devices (Telegram for Android v10.0.4 (3802))
Connect Button redirects to Tonkeeper download screen
Sign in with Tonkeeper gives webpage not available, net::ERR_UNKNOWN_URL_SCHEME

**To Reproduce**
1. Use Telegram for Android v10.0.4 (3802), also install TonKeeper android app
2. Click on `Connect Button`
3. Sigin in with TonKeeper
4. Error: Sign in with Tonkeeper gives webpage not available, net::ERR_UNKNOWN_URL_SCHEME

**Expected behavior**
It should redirect to Tonkeeper app, and it should connect the TWA

**Screenshots**
 - Telegram for Android v10.0.4 (3802)
 - Package version `"@tonconnect/ui-react": "^1.0.0-beta.9"`

**Additional context**
Attached a video for you ref

https://github.com/ton-connect/sdk/assets/58180803/413030f8-1af6-4de9-8fdc-09e75f6888e0

**Comment by jasonplato** [comment]
I got the same problem. Cannot find any solution to this. I guess it's the problem of tonconnect:// url

**Comment by siandreev** [comment]
Fixed in `@tonconnect/ui 2.0.0-beta.0`

**Comment by T-Damer** [comment]
Same started happening again on latest `2.0.9`
![telegram-cloud-photo-size-2-5195441219088540623-y](https://github.com/user-attachments/assets/a12930a8-fc1b-4564-868c-7fdef9989bab)

**Comment by Uzabiliti** [comment]
Здравствуйте, подскажите в чем может быть причина? На телефоне Honor I30 (Android) установлен кошелек Tonkeeper. При подключении кошелька к боту в Telegram кошелек не подключается и не определяется на телефоне, появляется предложение установить кошелек. Скрин прикрепил. Ранее до этой проблемы перестали приходить сообщения для подтверждения транзакции. Также, записал видео, где показано, что на телефоне установлен Тонкипер, затем перехожу в бота, клацаю по "Подключить кошелек", далее выбираю Tonkeeper и на этом всё, предлагает скачать и установить.

https://github.com/user-attachments/assets/802285cb-8304-4414-8d5b-f6d6b8b14287

![Image](https://github.com/user-attachments/assets/7e98c11b-3b45-4e32-9f1a-eb5ebf6a0b5d)
