### ISSUE TITLE
Error in Safari

### ISSUE THREAD

**Issue by Vanekchekarmam** [ton-connect/sdk#87]
Error in Safari

Compiled with problems:
×
ERROR
Illegal constructor
HTMLDivElement@[native code]
TcRootElement@
createElement@[native code]
@http://localhost:3000/static/js/bundle.js:16573:75
runComputation@http://localhost:3000/static/js/bundle.js:15619:24
updateComputation@http://localhost:3000/static/js/bundle.js:15612:17
createMemo@http://localhost:3000/static/js/bundle.js:15356:20
untrack@http://localhost:3000/static/js/bundle.js:15491:14
children@http://localhost:3000/static/js/bundle.js:24506:38
children@http://localhost:3000/static/js/bundle.js:16663:19
@http://localhost:3000/static/js/bundle.js:15802:34
runComputation@http://localhost:3000/static/js/bundle.js:15619:24
updateComputation@http://localhost:3000/static/js/bundle.js:15612:17
createMemo@http://localhost:3000/static/js/bundle.js:15356:20
children@http://localhost:3000/static/js/bundle.js:15541:31
untrack@http://localhost:3000/static/js/bundle.js:15491:14
@http://localhost:3000/static/js/bundle.js:15798:43
runComputation@http://localhost:3000/static/js/bundle.js:15619:24
updateComputation@http://localhost:3000/static/js/bundle.js:15612:17
createRenderEffect@http://localhost:3000/static/js/bundle.js:15342:20
provider@http://localhost:3000/static/js/bundle.js:15798:23

**Comment by siandreev** [comment]
Thanks for your contribution. Please, provide more details:
- repo with the project
- sdk, framework and bundler versions
- steps to reproduce
